on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Reviews
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          CHANGED_FILES=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/files --jq '.[].filename')
          
          declare -A PATH_APPROVERS
          PATH_APPROVERS=( 
            ["/adam/"]="adamvg" 
            ["/chris/"]="hardingchris"
            ["/both/"]="thejoeker12 hardingchris"
          )
         
          # Build required approvers list based on changed files
          REQUIRED_APPROVERS=()
          for path in "${!PATH_APPROVERS[@]}"; do
              if [[ $file == *"$path"* ]]; then
                # Split space-separated approvers into array
                IFS=' ' read -ra APPROVERS <<< "${PATH_APPROVERS[$path]}"
                REQUIRED_APPROVERS+=("${APPROVERS[@]}")
              fi
            done
          
          # Remove duplicates
          REQUIRED_APPROVERS=($(echo "${REQUIRED_APPROVERS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          
          # Get reviews
          REVIEWS=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews)
          
          # Check approvals
          for approver in "${REQUIRED_APPROVERS[@]}"; do
            if ! echo "$REVIEWS" | jq -e --arg approver "$approver" '.[] | select(.state=="APPROVED" and (.user.login==$approver or .user.teams[].name==$approver))' > /dev/null; then
              echo "Missing approval from $approver"
              exit 1
            fi
          done
          
          echo "All required approvals received"